application:
  title: Hotel Alura Api
  version: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/hotel_alura
    username: root
    password: 

  mail:
    host: smtp.gmail.com
    port: 587
    username: # username to login within the email account
    password: # password to login within the email account
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8090