application:
  title: Hotel Alura Api
  version: 1.0
  # TODO Change to production host
  front-end:
    host: https://waamir.dev

  security:
    jwt:
      secret:
        key: 6e1bd6c726bfbbf91c502b64b90b647aa7c3de9a5b6fd9e93652b7ce63b53b56

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: # username to login within the email account
    password: # password to login within the email account
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8090
  servlet:
    encoding:
      enabled: true
      charset: UTF-8

logging:
  level:
    org.springframework.security: DEBUG

cors:
  allowed:
    methods: PUT, POST, GET, DELETE
  maxAge: 3600
