application:
  title: Hotel Alura Api
  version: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/hotel_alura
    username: root
    password: root
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8090